name: Gh-Pages

on:
  push:
    branches: [preview]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /navigator_animation/
#